### ISSUE TITLE
Feature: Add Rich text formatting in insturctions component

### ISSUE THREAD

**Issue by rohansharmasitoula** [talview/moodle-quizaccess_proctor#27]
Feature: Add Rich text formatting in insturctions component

**Comment by Anil-R07** [comment]
@rohansharmasitoula Testing is completed on Moodle Testing, working as expected 

![Image](https://github.com/talview/moodle-quizaccess_proctor/assets/74236892/12eaaca9-a011-477c-9287-e3d226df1737)

![Image](https://github.com/talview/moodle-quizaccess_proctor/assets/74236892/7ceed629-2fab-4736-b105-31cbcc0b91f6)

![Image](https://github.com/talview/moodle-quizaccess_proctor/assets/74236892/64f1e26d-a8c5-4820-a7e6-0af851ae8a8e)
