### ISSUE TITLE
Feature | Moodle-Quizaccess_Proctor | Launch Exam on TSB if TSB enabled

### ISSUE THREAD

**Issue by rohansharmasitoula** [talview/moodle-quizaccess_proctor#35]
**Expected behaviour**: If tsb is enabled for the quizzes then launch the quiz in TSB browser

Solution: Extend the quizaccess rule base class of moodle and impement tsb launch on the attempt page setup.

**Testing Procdeures:**
1. create a quiz
2. select proctoring type
3. enable TSB 

![Image](https://github.com/talview/moodle-quizaccess_proctor/assets/100085662/8439aa22-65b8-4ca4-bf84-f19e36d30447)

**Comment by Anil-R07** [comment]
@rohansharmasitoula Tested on moodle lms 4.1, when ever the quiz is enable with TSB, when the candidate clicks on attend button it will open a pop up for launch TSb or download the TSB and launch
