### ISSUE TITLE
When proctoring is enabled, hide the back button

### ISSUE THREAD

**Issue by rohansharmasitoula** [talview/moodle-quizaccess_proctor#38]
When proctoring is enabled on moodle 4.1 version, a back button shows. Onclick of the back button, the quiz closes and proview session gets completed.

If proview is enabled, hide the back button.
<img width="865" alt="image" src="https://github.com/talview/moodle-quizaccess_proctor/assets/100085662/3c639bd4-2821-41df-96c7-6ede95ad1a72">

**Comment by Anil-R07** [comment]
@rohansharmasitoula validated on moodle 4.1, now the back button is disabled

**Comment by Anil-R07** [comment]
@rohansharmasitoula Tested on moodle 4.1 in normal and TSB, the back button is not available on the assessment screen 
![image](https://github.com/talview/moodle-quizaccess_proctor/assets/74236892/c73b10f9-6d51-456f-b781-a400891be955)
