### ISSUE TITLE
Change proctoring types dropdown in Moodle - Inspera 

### ISSUE THREAD

**Issue by rohansharmasitoula** [talview/moodle-quizaccess_proctor#42]
Change the drop-down options in Moodle from the existing options to display the new options as shown below:
No proctoring
Recorded
Record and Review
Live Proctoring

CC: @Othersh123

**Comment by Anil-R07** [comment]
@rohansharmasitoula tested on Moodle instance, working as expected 
![Image](https://github.com/talview/moodle-quizaccess_proctor/assets/74236892/8e02d210-38fc-46b0-beca-3f33bb5e31fb)

Did a sanity on all proctoring types, working as expected
