### ISSUE TITLE
[Quizaccess Proctor] [Moodle] Accept all configurations for secure browser

### ISSUE THREAD

**Issue by rohansharmasitoula** [talview/moodle-quizaccess_proctor#50]
User story-
As an admin,
I want to configure all possible configurations for the secure browser when configuring settings for a quiz in Moodle,
so that I can have a secure testing environment.

Configurations to be added in quiz creation page under "Proctoring Settings":
- [x] Blacklisted Apps (windows and mac)
- [x] Kiosk mode
- [x] Content Protection

**Describe the solution you'd like**
- Take all the configurations from UI and store in DB tagged to a quiz

**Comment by amithPatel21A** [comment]
Test cases link - https://test-management.browserstack.com/projects/218511/folder/4450810/test-cases

**Comment by Anil-R07** [comment]
@rohansharmasitoula Tested in https://moodle-lms-4-dev.talview.org/, working as expected 
Tested for the below mentioned scenarios 
1. SB Configurations 
2. Kiosk mode enabled - Minimizing screen is not allowed 
3. Screen protection enabled - won't capture the exam screenshots 
4. Kiosk mode disabled - Minimizing screen permitted 
5.  Screen protection disabled - Capture the exam screenshots 
6. Playback video is available 
![image](https://github.com/user-attachments/assets/1e0c64c2-5aa8-48d9-8f0c-a7e396c8e5e9)
Tested for both proctored and non proctored assessments
